using GovernmentTechnicalVocationalCollege.Application.Features.Instructors.Requests;
using GovernmentTechnicalVocationalCollege.Application.Features.Instructors.Responses;
using GovernmentTechnicalVocationalCollege.Domain.Entities;

namespace GovernmentTechnicalVocationalCollege.Application.Mappers.InstructorMappers;

public static class InstructorMapper
{
    // Create Request -> Teacher Entity
    public static Instructor MapToEntity(this CreateInstructorRequest request,string employeeNo)
    {
        var now = DateTime.UtcNow;

        return new Instructor
        {
            Id = Guid.NewGuid(),

            // Generated by the application service
            EmployeeNo = employeeNo,

            FirstName = request.FirstName,
            LastName = request.LastName,
            FatherName = request.FatherName,
            CNIC = request.CNIC,

            Phone = request.Phone,
            Email = request.Email,
            Address = request.Address,

            IsActive = true,

            CreatedAt = now,
            UpdatedAt = null
        };
    }

    // Update Request -> Existing Teacher Entity
    public static void MapToEntity( this UpdateInstructorRequest request,Instructor teacher)
    {
        teacher.FirstName = request.FirstName;
        teacher.LastName = request.LastName;
        teacher.FatherName = request.FatherName;
        teacher.CNIC = request.CNIC;

        teacher.Phone = request.Phone;
        teacher.Email = request.Email;
        teacher.Address = request.Address;

        teacher.IsActive = request.IsActive;
        teacher.UpdatedAt = DateTime.UtcNow;
    }

    // Teacher Entity -> List Response
    public static InstructorListResponse MapToListResponse(this Instructor teacher)
    {
        return new InstructorListResponse(
            teacher.Id,
            teacher.EmployeeNo,
            teacher.FirstName,
            teacher.LastName,
            teacher.CNIC,
            teacher.Phone,
            teacher.IsActive
        );
    }

    // Teacher Entity -> Details Response
    public static InstructorDetailsResponse MapToDetailsResponse( this Instructor teacher)
    {
        return new InstructorDetailsResponse(
            teacher.Id,
            teacher.EmployeeNo,
            teacher.FirstName,
            teacher.LastName,
            teacher.FatherName,
            teacher.CNIC,
            teacher.Phone,
            teacher.Email,
            teacher.Address,
            teacher.IsActive,
            teacher.CreatedAt,
            teacher.UpdatedAt
        );
    }
}